language: node_js
node_js: stable

# assign build branches
branches:
  only:
    - blog-source

# cache this directory
cache:
  directories:
    - node_modules

# S: Build Lifecycle
before_install:
  - npm install -g hexo-cli # 安装 hexo
  
install:
  - npm install # 安装 package.json 中的插件
  - npm i -g yuque-hexo
  
script:
  - yuque-hexo sync
  - hexo clean
  - hexo generate --watch

after_script:
  - cd ./public
  - git init
  - git config user.name "iyuwe6"
  - git config user.email "iyuwe6@163.com"
  - git add .
  - git commit -m "TravisCI 自动部署"
  # Github Pages
  - git push --force --quiet "https://${GithubToken}@${GH_REF}" master:master 
  # Coding Pages
  - git push --force --quiet "https://iyuwe:${CodingToken}@${CO_REF}" master:master

env:
 global:
   # Github Pages
   - GH_REF: github.com/iyuwe6/iyuwe6.github.io.git
   # Coding Pages
   - CO_REF: git.dev.tencent.com/iyuwe/iyuwe.coding.me.git
